[build]
  command = "GENERATE_SOURCEMAP=false CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
  autoLaunch = true

